name: Create and publish Docker Image

on: 
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      tag:
        type: string
    secrets:
      DOCKERHUB_USERNAME:
          required: true
      DOCKERHUB_PASSWORD:
          required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Login to Registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set the tag
        run: | 
          if [ -z "${{ inputs.tag }}" ]
          then
            echo "final_tag=latest" >> $GITHUB_ENV
          else
            echo "final_tag=${{ inputs.tag }}" >> $GITHUB_ENV
          fi
      - name: Build and Push the Image
        uses: docker/build-push-action@v2
        with: 
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME}}/${{inputs.image_name}}:${{env.final_tag}}
      
  do-something-else:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"
      
